"""Init db

Revision ID: fdda445fd413
Revises: 
Create Date: 2019-03-20 15:36:17.688242

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fdda445fd413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
                    sa.Column('admin_id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('admin_id'),
                    sa.UniqueConstraint('chat_id')
                    )
    op.create_table('wall_posts',
                    sa.Column('wall_post_id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('wall_post_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wall_posts')
    op.drop_table('admins')
    # ### end Alembic commands ###
