"""Add Porfile

Revision ID: 4350e0683395
Revises: fdda445fd413
Create Date: 2019-03-20 15:38:43.846273

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4350e0683395'
down_revision = 'fdda445fd413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
                    sa.Column('profile_id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('profile_id')
                    )
    op.add_column('wall_posts', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wall_posts', 'profiles', ['profile_id'], ['profile_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wall_posts', type_='foreignkey')
    op.drop_column('wall_posts', 'profile_id')
    op.drop_table('profiles')
    # ### end Alembic commands ###
