"""Add likes comment message_id

Revision ID: c74d72bce31b
Revises: 4350e0683395
Create Date: 2019-03-21 19:57:28.963205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74d72bce31b'
down_revision = '4350e0683395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wall_posts', sa.Column('comments', sa.Integer(), nullable=True))
    op.add_column('wall_posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('wall_posts', sa.Column('message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wall_posts', 'message_id')
    op.drop_column('wall_posts', 'likes')
    op.drop_column('wall_posts', 'comments')
    # ### end Alembic commands ###
